-- 乐观锁版本字段
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE sys_dept ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
ALTER TABLE sys_config ADD COLUMN IF NOT EXISTS version INT DEFAULT 0;
